package com.fourlt.party;

import com.fourlt.party.Person;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("\u0421\u0442\u0430\u0436")
public class Experience extends Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("\u0414\u0430\u0442\u0430 \u043E\u043A\u043E\u043D\u0447\u0430\u043D\u0438\u044F \u0440\u0430\u0431\u043E\u0442\u044B")
	@org.kie.api.definition.type.Position(2)
	private java.util.Date endDate;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0441\u0442\u0430\u0436\u0430")
	@org.kie.api.definition.type.Position(0)
	private java.lang.Integer experienceID;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u0438")
	@org.kie.api.definition.type.Position(3)
	private java.lang.Integer organisationID;

    @org.kie.api.definition.type.Label("\u0414\u0430\u0442\u0430 \u043D\u0430\u0447\u0430\u043B\u0430 \u0437\u0430\u043D\u044F\u0442\u043E\u0441\u0442\u0438")
	@org.kie.api.definition.type.Position(1)
	private java.util.Date startDate;

    public java.util.Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(java.util.Date endDate) {
        this.endDate = endDate;
    }

    public java.lang.Integer getExperienceID() {
        return this.experienceID;
    }
    
    public void setExperienceID(java.lang.Integer experienceID) {
        this.experienceID = experienceID;
    }

    public java.lang.Integer getOrganisationID() {
        return this.organisationID;
    }
    
    public void setOrganisationID(java.lang.Integer organisationID) {
        this.organisationID = organisationID;
    }

    public java.util.Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(java.util.Date startDate) {
        this.startDate = startDate;
    }

	public Experience() {
	}

	public Experience(java.lang.Integer experienceID, java.util.Date startDate,
			java.util.Date endDate, java.lang.Integer organisationID) {
		this.experienceID = experienceID;
		this.startDate = startDate;
		this.endDate = endDate;
		this.organisationID = organisationID;
	}

}