package com.fourlt.party;

import com.fourlt.reference.Country;
import com.fourlt.party.Party;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("\u041F\u0435\u0440\u0441\u043E\u043D\u0430")
public class Person extends Party implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0430\u0432\u0442\u043E\u043D\u043E\u043C\u0438\u0438")
	@org.kie.api.definition.type.Position(5)
	private java.lang.Integer autonomyCode;

    @org.kie.api.definition.type.Label("\u0434\u0430\u0442\u0430 \u0440\u043E\u0436\u0434\u0435\u043D\u0438\u044F")
	@org.kie.api.definition.type.Position(1)
	private java.util.Date birthDate;

    @org.kie.api.definition.type.Label("\u041A\u043E\u0434 \u0433\u043E\u0440\u043E\u0434\u0430 \u0440\u043E\u0436\u0434\u0435\u043D\u0438\u044F")
	@org.kie.api.definition.type.Position(3)
	private java.lang.Integer cityBirthCode;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0441\u0442\u0440\u0430\u043D\u044B ISO3")
	@org.kie.api.definition.type.Position(7)
	private Country countryISO3;

    @org.kie.api.definition.type.Label("\u0434\u0430\u0442\u0430 \u0441\u043C\u0435\u0440\u0442\u0438")
	@org.kie.api.definition.type.Position(2)
	private java.util.Date deathDate;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0440\u0430\u0439\u043E\u043D\u0430")
	@org.kie.api.definition.type.Position(4)
	private java.lang.Integer districtCode;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0440\u043E\u0434\u043D\u043E\u0433\u043E \u044F\u0437\u044B\u043A\u0430")
	@org.kie.api.definition.type.Position(0)
	private java.lang.Integer motherLanguageCode;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0440\u0435\u0433\u0438\u043E\u043D\u0430")
	@org.kie.api.definition.type.Position(6)
	private java.lang.Integer regionCode;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
	@org.kie.api.definition.type.Position(8)
	private java.lang.Integer subjectID;

<<<<<<< HEAD
    public java.lang.Integer getAutonomyCode() {
=======
    @org.kie.api.definition.type.Label(value = "\u0418\u043C\u044F")
	@org.kie.api.definition.type.Position(value = 9)
	private java.lang.String fistName;

	@org.kie.api.definition.type.Label(value = "\u0424\u0430\u043C\u0438\u043B\u0438\u044F")
	@org.kie.api.definition.type.Position(value = 10)
	private java.lang.String lastName;

	@org.kie.api.definition.type.Label(value = "\u041E\u0442\u0447\u0435\u0442\u0441\u0442\u0432\u043E")
	@org.kie.api.definition.type.Position(value = 11)
	private java.lang.String middleName;

	public java.lang.Integer getAutonomyCode() {
>>>>>>> remotes/4LTGithub/master
        return this.autonomyCode;
    }
    
    public void setAutonomyCode(java.lang.Integer autonomyCode) {
        this.autonomyCode = autonomyCode;
    }

    public java.util.Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(java.util.Date birthDate) {
        this.birthDate = birthDate;
    }

    public java.lang.Integer getCityBirthCode() {
        return this.cityBirthCode;
    }
    
    public void setCityBirthCode(java.lang.Integer cityBirthCode) {
        this.cityBirthCode = cityBirthCode;
    }

    public java.util.Date getDeathDate() {
        return this.deathDate;
    }
    
    public void setDeathDate(java.util.Date deathDate) {
        this.deathDate = deathDate;
    }

    public java.lang.Integer getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(java.lang.Integer districtCode) {
        this.districtCode = districtCode;
    }

    public java.lang.Integer getMotherLanguageCode() {
        return this.motherLanguageCode;
    }
    
    public void setMotherLanguageCode(java.lang.Integer motherLanguageCode) {
        this.motherLanguageCode = motherLanguageCode;
    }

    public java.lang.Integer getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(java.lang.Integer regionCode) {
        this.regionCode = regionCode;
    }

    public java.lang.Integer getSubjectID() {
        return this.subjectID;
    }
    
    public void setSubjectID(java.lang.Integer subjectID) {
        this.subjectID = subjectID;
    }

	public com.fourlt.reference.Country getCountryISO3() {
		return this.countryISO3;
	}

	public void setCountryISO3(com.fourlt.reference.Country countryISO3) {
		this.countryISO3 = countryISO3;
	}

<<<<<<< HEAD
=======
	public java.lang.String getFistName() {
		return this.fistName;
	}

	public void setFistName(java.lang.String fistName) {
		this.fistName = fistName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(java.lang.String middleName) {
		this.middleName = middleName;
	}

>>>>>>> remotes/4LTGithub/master
	public Person() {
	}

	public Person(java.lang.Integer motherLanguageCode,
			java.util.Date birthDate, java.util.Date deathDate,
			java.lang.Integer cityBirthCode, java.lang.Integer districtCode,
			java.lang.Integer autonomyCode, java.lang.Integer regionCode,
			com.fourlt.reference.Country countryISO3,
<<<<<<< HEAD
			java.lang.Integer subjectID) {
=======
			java.lang.Integer subjectID, java.lang.String fistName,
			java.lang.String lastName, java.lang.String middleName) {
>>>>>>> remotes/4LTGithub/master
		this.motherLanguageCode = motherLanguageCode;
		this.birthDate = birthDate;
		this.deathDate = deathDate;
		this.cityBirthCode = cityBirthCode;
		this.districtCode = districtCode;
		this.autonomyCode = autonomyCode;
		this.regionCode = regionCode;
		this.countryISO3 = countryISO3;
		this.subjectID = subjectID;
<<<<<<< HEAD
=======
		this.fistName = fistName;
		this.lastName = lastName;
		this.middleName = middleName;
>>>>>>> remotes/4LTGithub/master
	}

}