package com.fourlt.subject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("\u0417\u0430\u043D\u044F\u0442\u043E\u0441\u0442\u044C")
public class employment extends com.fourlt.subject.Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("\u0422\u0438\u043F \u0434\u043E\u043B\u0436\u043D\u043E\u0441\u0442\u0438")
	@org.kie.api.definition.type.Position(3)
	private char positionType;

    @org.kie.api.definition.type.Label("\u0432\u0430\u043B\u044E\u0442\u0430 \u0434\u043E\u0445\u043E\u0434\u0430")
	@org.kie.api.definition.type.Position(2)
	private char wagesCurrency;

    @org.kie.api.definition.type.Label("\u0437\u0430\u044F\u0432\u043B\u0435\u043D\u043D\u044B\u0439  \u0434\u043E\u0445\u043E\u0434")
	@org.kie.api.definition.type.Position(0)
	private java.lang.Integer wagesDeclared;

    @org.kie.api.definition.type.Label("\u0434\u043E\u0445\u043E\u0434 \u043F\u043E\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043D\u043D\u044B\u0439")
	@org.kie.api.definition.type.Position(1)
	private java.lang.Integer wagesVerifed;

    @org.kie.api.definition.type.Label("\u0441\u0444\u0435\u0440\u0430 \u0434\u0435\u044F\u0442\u0435\u043B\u044C\u043D\u043E\u0441\u0442\u0438")
	@org.kie.api.definition.type.Position(4)
	private char referenceFrame;

	@org.kie.api.definition.type.Label("\u0422\u0438\u043F \u0434\u043E\u0445\u043E\u0434\u0430")
	@org.kie.api.definition.type.Position(5)
	@org.kie.api.definition.type.Description("\u043E\u0441\u043D\u043E\u0432\u043D\u043E\u0439 \u0438\u043B\u0438 \u043F\u0440\u043E\u0447\u0438\u0435 \u0434\u043E\u0445\u043E\u0434\u044B")
	private char wagesType;

	@org.kie.api.definition.type.Label(value = "\u0434\u043E\u0445\u043E\u0434 \u0441\u0443\u043F\u0440\u0443\u0433\u0430")
	@org.kie.api.definition.type.Position(value = 6)
	private char spouseWages;

	public char getPositionType() {
        return this.positionType;
    }
    
    public void setPositionType(char positionType) {
        this.positionType = positionType;
    }

    public char getWagesCurrency() {
        return this.wagesCurrency;
    }
    
    public void setWagesCurrency(char wagesCurrency) {
        this.wagesCurrency = wagesCurrency;
    }

    public java.lang.Integer getWagesDeclared() {
        return this.wagesDeclared;
    }
    
    public void setWagesDeclared(java.lang.Integer wagesDeclared) {
        this.wagesDeclared = wagesDeclared;
    }

    public java.lang.Integer getWagesVerifed() {
        return this.wagesVerifed;
    }
    
    public void setWagesVerifed(java.lang.Integer wagesVerifed) {
        this.wagesVerifed = wagesVerifed;
    }

	public char getReferenceFrame() {
		return this.referenceFrame;
	}

	public void setReferenceFrame(char referenceFrame) {
		this.referenceFrame = referenceFrame;
	}

	public char getWagesType() {
		return this.wagesType;
	}

	public void setWagesType(char wagesType) {
		this.wagesType = wagesType;
	}

	public char getSpouseWages() {
		return this.spouseWages;
	}

	public void setSpouseWages(char spouseWages) {
		this.spouseWages = spouseWages;
	}

	public employment() {
	}

	public employment(java.lang.Integer wagesDeclared,
			java.lang.Integer wagesVerifed, char wagesCurrency,
			char positionType, char referenceFrame, char wagesType,
			char spouseWages) {
		this.wagesDeclared = wagesDeclared;
		this.wagesVerifed = wagesVerifed;
		this.wagesCurrency = wagesCurrency;
		this.positionType = positionType;
		this.referenceFrame = referenceFrame;
		this.wagesType = wagesType;
		this.spouseWages = spouseWages;
	}

}