package com.fourlt.subject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "\u0417\u0430\u043D\u044F\u0442\u043E\u0441\u0442\u044C")
public class employment extends com.fourlt.subject.Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "\u0422\u0438\u043F \u0434\u043E\u043B\u0436\u043D\u043E\u0441\u0442\u0438")
    @org.kie.api.definition.type.Position(value = 3)
    private char positionType;

    @org.kie.api.definition.type.Label(value = "\u0432\u0430\u043B\u044E\u0442\u0430 \u0434\u043E\u0445\u043E\u0434\u0430")
    @org.kie.api.definition.type.Position(value = 2)
    private char wagesCurrency;

    @org.kie.api.definition.type.Label(value = "\u0437\u0430\u044F\u0432\u043B\u0435\u043D\u043D\u044B\u0439  \u0434\u043E\u0445\u043E\u0434")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer wagesDeclared;

    @org.kie.api.definition.type.Label(value = "\u0434\u043E\u0445\u043E\u0434 \u043F\u043E\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043D\u043D\u044B\u0439")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer wagesVerifed;

    public employment() {
    }
    
    public employment(java.lang.Integer wagesDeclared, java.lang.Integer wagesVerifed, char wagesCurrency, char positionType) {
        this.wagesDeclared = wagesDeclared;
        this.wagesVerifed = wagesVerifed;
        this.wagesCurrency = wagesCurrency;
        this.positionType = positionType;
    }

    public char getPositionType() {
        return this.positionType;
    }
    
    public void setPositionType(char positionType) {
        this.positionType = positionType;
    }

    public char getWagesCurrency() {
        return this.wagesCurrency;
    }
    
    public void setWagesCurrency(char wagesCurrency) {
        this.wagesCurrency = wagesCurrency;
    }

    public java.lang.Integer getWagesDeclared() {
        return this.wagesDeclared;
    }
    
    public void setWagesDeclared(java.lang.Integer wagesDeclared) {
        this.wagesDeclared = wagesDeclared;
    }

    public java.lang.Integer getWagesVerifed() {
        return this.wagesVerifed;
    }
    
    public void setWagesVerifed(java.lang.Integer wagesVerifed) {
        this.wagesVerifed = wagesVerifed;
    }

}