package com.fourlt.subject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description(value = "\u0433\u0435\u043E\u0433\u0440\u0430\u0444\u0438\u0447\u0435\u0441\u043A\u0430\u044F \u043B\u043E\u043A\u0430\u0446\u0438\u044F \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
@org.kie.api.definition.type.Label(value = "\u0433\u0435\u043E\u0431\u044A\u0435\u043A\u0442 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
public class GeoObject extends com.fourlt.subject.Subject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "\u043A\u043E\u0434 \u0430\u0432\u0442\u043E\u043D\u043E\u043C\u0438\u0438")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer autonomyCode;

    @org.kie.api.definition.type.Label(value = "\u041D\u043E\u043C\u0435\u0440 \u0441\u0442\u0440\u043E\u0435\u043D\u0438\u044F")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.Integer buildingNumber;

    @org.kie.api.definition.type.Label(value = "\u041A\u043E\u0434 \u0433\u043E\u0440\u043E\u0434\u0430")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer cityCode;

    @org.kie.api.definition.type.Label(value = "\u043A\u043E\u0434 \u0441\u0442\u0440\u0430\u043D\u044B ISO3")
    @org.kie.api.definition.type.Position(value = 5)
    private com.fourlt.subject.Country countryCodeISO3;

    @org.kie.api.definition.type.Label(value = "\u041A\u043E\u0434 \u0440\u0430\u0439\u043E\u043D\u0430")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer districtCode;

    @org.kie.api.definition.type.Label(value = "\u041A\u043E\u0434 \u0433\u0435\u043E\u0431\u043E\u0431\u044A\u0435\u043A\u0442\u0430")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer geoObjectCode;

    @org.kie.api.definition.type.Label(value = "\u043D\u043E\u043C\u0435\u0440 \u0434\u043E\u043C\u0430")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Integer houseNumber;

    @org.kie.api.definition.type.Label(value = "\u043A\u043E\u0434 \u0440\u0435\u0433\u0438\u043E\u043D\u0430")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer regionCode;

    public GeoObject() {
    }
    
    public GeoObject(java.lang.Integer geoObjectCode, java.lang.Integer cityCode, java.lang.Integer districtCode, java.lang.Integer autonomyCode, java.lang.Integer regionCode, com.fourlt.subject.Country countryCodeISO3, java.lang.Integer houseNumber, java.lang.Integer buildingNumber) {
        this.geoObjectCode = geoObjectCode;
        this.cityCode = cityCode;
        this.districtCode = districtCode;
        this.autonomyCode = autonomyCode;
        this.regionCode = regionCode;
        this.countryCodeISO3 = countryCodeISO3;
        this.houseNumber = houseNumber;
        this.buildingNumber = buildingNumber;
    }

    public java.lang.Integer getAutonomyCode() {
        return this.autonomyCode;
    }
    
    public void setAutonomyCode(java.lang.Integer autonomyCode) {
        this.autonomyCode = autonomyCode;
    }

    public java.lang.Integer getBuildingNumber() {
        return this.buildingNumber;
    }
    
    public void setBuildingNumber(java.lang.Integer buildingNumber) {
        this.buildingNumber = buildingNumber;
    }

    public java.lang.Integer getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(java.lang.Integer cityCode) {
        this.cityCode = cityCode;
    }

    public com.fourlt.subject.Country getCountryCodeISO3() {
        return this.countryCodeISO3;
    }
    
    public void setCountryCodeISO3(com.fourlt.subject.Country countryCodeISO3) {
        this.countryCodeISO3 = countryCodeISO3;
    }

    public java.lang.Integer getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(java.lang.Integer districtCode) {
        this.districtCode = districtCode;
    }

    public java.lang.Integer getGeoObjectCode() {
        return this.geoObjectCode;
    }
    
    public void setGeoObjectCode(java.lang.Integer geoObjectCode) {
        this.geoObjectCode = geoObjectCode;
    }

    public java.lang.Integer getHouseNumber() {
        return this.houseNumber;
    }
    
    public void setHouseNumber(java.lang.Integer houseNumber) {
        this.houseNumber = houseNumber;
    }

    public java.lang.Integer getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(java.lang.Integer regionCode) {
        this.regionCode = regionCode;
    }

}