package com.fourlt.subject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "\u0441\u0443\u0431\u044A\u0435\u043A\u0442")
@org.kie.api.definition.type.PropertyReactive
public class subject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Description(value = "\u043D\u043E\u043C\u0435\u0440 \u0418\u041D\u041D \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
    @org.kie.api.definition.type.Label(value = "\u0438\u043D\u043D")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer inn;

    @org.kie.api.definition.type.Description(value = "\u043A\u043E\u0434 \u043F\u0440\u0435\u0434\u043F\u043E\u0447\u0438\u0442\u0430\u0435\u043C\u043E\u0433\u043E \u044F\u0437\u044B\u043A\u0430")
    @org.kie.api.definition.type.Label(value = "\u044F\u0437\u044B\u043A")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer language;

    @org.kie.api.definition.type.Description(value = "\u0441\u0441\u044B\u043B\u043A\u0430 \u043D\u0430 \u0440\u043E\u0434\u0438\u0442\u0435\u043B\u044C\u0441\u043A\u0438\u0439 \u0438\u0434 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
    @org.kie.api.definition.type.Label(value = "\u0420\u043E\u0434\u0438\u0442\u0435\u043B\u044C\u0441\u043A\u0438\u0439 \u0438\u0434 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer parent_id;

    @org.kie.api.definition.type.Description(value = "\u0438\u0434 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
    @org.kie.api.definition.type.Label(value = "\u043A\u043E\u0434 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer subject_id;

    @org.kie.api.definition.type.Description(value = "\u0422\u0438\u043F \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430: \u0444\u0438\u0437\u0438\u0447\u0435\u0441\u043A\u043E\u0435 \u043B\u0438\u0446\u043E, \u0438\u043D\u0434\u0438\u0432\u0438\u0434\u0443\u0430\u043B\u044C\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043F\u0440\u0438\u043D\u0438\u043C\u0430\u0442\u0435\u043B\u044C, \u043E\u043E\u043E \u0438 \u0442\u0434")
    @org.kie.api.definition.type.Label(value = "\u0442\u0438\u043F \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
    @org.kie.api.definition.type.Position(value = 3)
    private char subject_type;

    public subject() {
    }
    
    public subject(java.lang.Integer subject_id, java.lang.Integer inn, java.lang.Integer language, char subject_type, java.lang.Integer parent_id) {
        this.subject_id = subject_id;
        this.inn = inn;
        this.language = language;
        this.subject_type = subject_type;
        this.parent_id = parent_id;
    }

    public java.lang.Integer getInn() {
        return this.inn;
    }
    
    public void setInn(java.lang.Integer inn) {
        this.inn = inn;
    }

    public java.lang.Integer getLanguage() {
        return this.language;
    }
    
    public void setLanguage(java.lang.Integer language) {
        this.language = language;
    }

    public java.lang.Integer getParent_id() {
        return this.parent_id;
    }
    
    public void setParent_id(java.lang.Integer parent_id) {
        this.parent_id = parent_id;
    }

    public java.lang.Integer getSubject_id() {
        return this.subject_id;
    }
    
    public void setSubject_id(java.lang.Integer subject_id) {
        this.subject_id = subject_id;
    }

    public char getSubject_type() {
        return this.subject_type;
    }
    
    public void setSubject_type(char subject_type) {
        this.subject_type = subject_type;
    }

}