package com.fourlt.subject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "\u0441\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A \u0442\u0438\u043F\u043E\u0432 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u043E\u0432")
public class subject_type implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public subject_type() {
    }

}