package application;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "\u0430\u043D\u043A\u0435\u0442\u0430\u041F\u0440\u043E\u0434\u0443\u043A\u0442")
public class ApplicationProduct implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "\u0414\u0430\u0442\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F \u0437\u0430\u044F\u0432\u043A\u0438")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date applicationCreateDate;

    @org.kie.api.definition.type.Label(value = "\u041A\u043E\u0434 \u0437\u0430\u044F\u0432\u043A\u0438")
    @org.kie.api.definition.type.Position(value = 0)
    private char applicationId;

    @org.kie.api.definition.type.Label(value = "\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F \u0441\u0443\u043C\u043C\u0430")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer approvedAmount;

    @org.kie.api.definition.type.Label(value = "\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F \u0432\u0430\u043B\u044E\u0442\u0430")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer approvedCurrencyId;

    @org.kie.api.definition.type.Label(value = "\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u044B\u0439 \u043F\u0440\u043E\u0434\u0443\u043A\u0442")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer approvedProductId;

    public ApplicationProduct() {
    }
    
    public ApplicationProduct(char applicationId, java.util.Date applicationCreateDate, java.lang.Integer approvedProductId, java.lang.Integer approvedAmount, java.lang.Integer approvedCurrencyId) {
        this.applicationId = applicationId;
        this.applicationCreateDate = applicationCreateDate;
        this.approvedProductId = approvedProductId;
        this.approvedAmount = approvedAmount;
        this.approvedCurrencyId = approvedCurrencyId;
    }

    public java.util.Date getApplicationCreateDate() {
        return this.applicationCreateDate;
    }
    
    public void setApplicationCreateDate(java.util.Date applicationCreateDate) {
        this.applicationCreateDate = applicationCreateDate;
    }

    public char getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(char applicationId) {
        this.applicationId = applicationId;
    }

    public java.lang.Integer getApprovedAmount() {
        return this.approvedAmount;
    }
    
    public void setApprovedAmount(java.lang.Integer approvedAmount) {
        this.approvedAmount = approvedAmount;
    }

    public java.lang.Integer getApprovedCurrencyId() {
        return this.approvedCurrencyId;
    }
    
    public void setApprovedCurrencyId(java.lang.Integer approvedCurrencyId) {
        this.approvedCurrencyId = approvedCurrencyId;
    }

    public java.lang.Integer getApprovedProductId() {
        return this.approvedProductId;
    }
    
    public void setApprovedProductId(java.lang.Integer approvedProductId) {
        this.approvedProductId = approvedProductId;
    }

}