package application;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("\u0430\u043D\u043A\u0435\u0442\u0430\u041F\u0440\u043E\u0434\u0443\u043A\u0442")
public class ApplicationProduct implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("\u0414\u0430\u0442\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F \u0437\u0430\u044F\u0432\u043A\u0438")
	@org.kie.api.definition.type.Position(1)
	private java.util.Date applicationCreateDate;

    @org.kie.api.definition.type.Label("\u041A\u043E\u0434 \u0437\u0430\u044F\u0432\u043A\u0438")
	@org.kie.api.definition.type.Position(0)
	private char applicationId;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F \u0441\u0443\u043C\u043C\u0430")
	@org.kie.api.definition.type.Position(3)
	private java.lang.Integer approvedAmount;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F \u0432\u0430\u043B\u044E\u0442\u0430")
	@org.kie.api.definition.type.Position(4)
	private java.lang.Integer approvedCurrencyId;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u044B\u0439 \u043F\u0440\u043E\u0434\u0443\u043A\u0442")
	@org.kie.api.definition.type.Position(2)
	private java.lang.Integer approvedProductId;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F \u0441\u0442\u0430\u0432\u043A\u0430")
	@org.kie.api.definition.type.Position(5)
	private java.lang.Integer approvedRate;

	@org.kie.api.definition.type.Label("\u043E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u044B\u0439 \u0441\u0440\u043E\u043A")
	@org.kie.api.definition.type.Position(6)
	private java.lang.Integer approvedMaturity;

	@org.kie.api.definition.type.Label("\u0417\u0430\u044F\u0432\u043B\u0435\u043D\u043D\u0430\u044F \u043F\u0440\u043E\u0446\u0435\u043D\u0442\u043D\u0430\u044F \u0441\u0442\u0430\u0432\u043A\u0430")
	@org.kie.api.definition.type.Position(7)
	private java.lang.Integer baseInterestRate;

	@org.kie.api.definition.type.Label("\u0422\u0438\u043F \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0430 \u041C\u0424\u041E")
	@org.kie.api.definition.type.Position(8)
	private java.lang.Integer contractTypeMFI;

	@org.kie.api.definition.type.Label("\u0421\u043E\u0432\u043E\u043A\u0443\u043F\u043D\u044B\u0439 \u0434\u043E\u0445\u043E\u0434")
	@org.kie.api.definition.type.Position(9)
	private java.lang.Integer grossIncomeSubject;

	@org.kie.api.definition.type.Label(value = "\u0421\u0442\u043E\u0438\u043C\u043E\u0441\u0442\u044C \u0441\u0442\u0440\u0430\u0445\u043E\u0432\u043A\u0438")
	@org.kie.api.definition.type.Position(value = 10)
	private java.lang.Integer insuranceAmount;

	@org.kie.api.definition.type.Label(value = "\u041A\u043E\u0434 \u0441\u0442\u0440\u0430\u0445\u043E\u0432\u043E\u0439 \u043A\u043E\u043C\u043F\u0430\u043D\u0438\u0438")
	@org.kie.api.definition.type.Position(value = 11)
	private java.lang.Integer insuranceCompanyId;

	@org.kie.api.definition.type.Label(value = "\u043A\u043E\u0434 \u0441\u0442\u0440\u0430\u0445\u043E\u0432\u043E\u0439 \u043F\u0440\u043E\u0433\u0440\u0430\u043C\u043C\u044B")
	@org.kie.api.definition.type.Position(value = 12)
	private java.lang.Integer insuranceProgramCode;

	public java.util.Date getApplicationCreateDate() {
        return this.applicationCreateDate;
    }
    
    public void setApplicationCreateDate(java.util.Date applicationCreateDate) {
        this.applicationCreateDate = applicationCreateDate;
    }

    public char getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(char applicationId) {
        this.applicationId = applicationId;
    }

    public java.lang.Integer getApprovedAmount() {
        return this.approvedAmount;
    }
    
    public void setApprovedAmount(java.lang.Integer approvedAmount) {
        this.approvedAmount = approvedAmount;
    }

    public java.lang.Integer getApprovedCurrencyId() {
        return this.approvedCurrencyId;
    }
    
    public void setApprovedCurrencyId(java.lang.Integer approvedCurrencyId) {
        this.approvedCurrencyId = approvedCurrencyId;
    }

    public java.lang.Integer getApprovedProductId() {
        return this.approvedProductId;
    }
    
    public void setApprovedProductId(java.lang.Integer approvedProductId) {
        this.approvedProductId = approvedProductId;
    }

	public java.lang.Integer getApprovedRate() {
		return this.approvedRate;
	}

	public void setApprovedRate(java.lang.Integer approvedRate) {
		this.approvedRate = approvedRate;
	}

	public java.lang.Integer getApprovedMaturity() {
		return this.approvedMaturity;
	}

	public void setApprovedMaturity(java.lang.Integer approvedMaturity) {
		this.approvedMaturity = approvedMaturity;
	}

	public java.lang.Integer getBaseInterestRate() {
		return this.baseInterestRate;
	}

	public void setBaseInterestRate(java.lang.Integer baseInterestRate) {
		this.baseInterestRate = baseInterestRate;
	}

	public java.lang.Integer getContractTypeMFI() {
		return this.contractTypeMFI;
	}

	public void setContractTypeMFI(java.lang.Integer contractTypeMFI) {
		this.contractTypeMFI = contractTypeMFI;
	}

	public java.lang.Integer getGrossIncomeSubject() {
		return this.grossIncomeSubject;
	}

	public void setGrossIncomeSubject(java.lang.Integer grossIncomeSubject) {
		this.grossIncomeSubject = grossIncomeSubject;
	}

	public java.lang.Integer getInsuranceAmount() {
		return this.insuranceAmount;
	}

	public void setInsuranceAmount(java.lang.Integer insuranceAmount) {
		this.insuranceAmount = insuranceAmount;
	}

	public java.lang.Integer getInsuranceCompanyId() {
		return this.insuranceCompanyId;
	}

	public void setInsuranceCompanyId(java.lang.Integer insuranceCompanyId) {
		this.insuranceCompanyId = insuranceCompanyId;
	}

	public java.lang.Integer getInsuranceProgramCode() {
		return this.insuranceProgramCode;
	}

	public void setInsuranceProgramCode(java.lang.Integer insuranceProgramCode) {
		this.insuranceProgramCode = insuranceProgramCode;
	}

	public ApplicationProduct() {
	}

	public ApplicationProduct(char applicationId,
			java.util.Date applicationCreateDate,
			java.lang.Integer approvedProductId,
			java.lang.Integer approvedAmount,
			java.lang.Integer approvedCurrencyId,
			java.lang.Integer approvedRate, java.lang.Integer approvedMaturity,
			java.lang.Integer baseInterestRate,
			java.lang.Integer contractTypeMFI,
			java.lang.Integer grossIncomeSubject,
			java.lang.Integer insuranceAmount,
			java.lang.Integer insuranceCompanyId,
			java.lang.Integer insuranceProgramCode) {
		this.applicationId = applicationId;
		this.applicationCreateDate = applicationCreateDate;
		this.approvedProductId = approvedProductId;
		this.approvedAmount = approvedAmount;
		this.approvedCurrencyId = approvedCurrencyId;
		this.approvedRate = approvedRate;
		this.approvedMaturity = approvedMaturity;
		this.baseInterestRate = baseInterestRate;
		this.contractTypeMFI = contractTypeMFI;
		this.grossIncomeSubject = grossIncomeSubject;
		this.insuranceAmount = insuranceAmount;
		this.insuranceCompanyId = insuranceCompanyId;
		this.insuranceProgramCode = insuranceProgramCode;
	}

}