package application;

import com.fourlt.reference.currencyCode;
import com.fourlt.party.Party;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("\u0410\u043D\u043A\u0435\u0442\u0430\u041F\u0440\u043E\u0434\u0443\u043A\u0442")
public class ApplicationProduct implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("\u0414\u0430\u0442\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F \u0437\u0430\u044F\u0432\u043A\u0438")
	@org.kie.api.definition.type.Position(1)
	private java.util.Date applicationCreateDate;

    @org.kie.api.definition.type.Label("\u041A\u043E\u0434 \u0437\u0430\u044F\u0432\u043A\u0438")
	@org.kie.api.definition.type.Position(0)
	private char applicationId;

    @org.kie.api.definition.type.Label("\u0417\u0430\u043F\u0440\u0430\u0448\u0438\u0432\u0430\u0435\u043C\u0430\u044F \u0441\u0443\u043C\u043C\u0430")
	@org.kie.api.definition.type.Position(3)
	private java.lang.Integer requestedAmount;

    @org.kie.api.definition.type.Label("\u0417\u0430\u043F\u0440\u0430\u0432\u0448\u0438\u0432\u0430\u0435\u043C\u0430\u044F \u0432\u0430\u043B\u044E\u0442\u0430")
	@org.kie.api.definition.type.Position(4)
	private currencyCode requestedCurrencyId;

    @org.kie.api.definition.type.Label("\u0417\u0430\u043F\u0440\u0430\u0448\u0438\u0432\u0430\u0435\u043C\u044B\u0439 \u043F\u0440\u043E\u0434\u0443\u043A\u0442")
	@org.kie.api.definition.type.Position(2)
	private char requestedProductId;

    @org.kie.api.definition.type.Label("\u0417\u0430\u043F\u0440\u0430\u0448\u0438\u0432\u0430\u0435\u043C\u0430\u044F \u0441\u0442\u0430\u0432\u043A\u0430")
	@org.kie.api.definition.type.Position(5)
	private java.lang.Integer requestedRate;

	@org.kie.api.definition.type.Label("\u0417\u0430\u043F\u0440\u0430\u0448\u0438\u0432\u0430\u0435\u043C\u044B\u0439 \u0441\u0440\u043E\u043A")
	@org.kie.api.definition.type.Position(6)
	private java.lang.Integer requestedMaturity;

	@org.kie.api.definition.type.Label("\u0417\u0430\u044F\u0432\u043B\u0435\u043D\u043D\u0430\u044F \u043F\u0440\u043E\u0446\u0435\u043D\u0442\u043D\u0430\u044F \u0441\u0442\u0430\u0432\u043A\u0430")
	@org.kie.api.definition.type.Position(7)
	private java.lang.Integer baseInterestRate;

	@org.kie.api.definition.type.Label("\u0422\u0438\u043F \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0430 \u041C\u0424\u041E")
	@org.kie.api.definition.type.Position(8)
	private char contractTypeMFI;

	@org.kie.api.definition.type.Label("\u0421\u0442\u043E\u0438\u043C\u043E\u0441\u0442\u044C \u0441\u0442\u0440\u0430\u0445\u043E\u0432\u043A\u0438")
	@org.kie.api.definition.type.Position(9)
	private java.lang.Integer insuranceAmount;

	@org.kie.api.definition.type.Label("\u041A\u043E\u0434 \u0441\u0442\u0440\u0430\u0445\u043E\u0432\u043E\u0439 \u043A\u043E\u043C\u043F\u0430\u043D\u0438\u0438")
	@org.kie.api.definition.type.Position(10)
	private char insuranceCompanyId;

	@org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0441\u0442\u0440\u0430\u0445\u043E\u0432\u043E\u0439 \u043F\u0440\u043E\u0433\u0440\u0430\u043C\u043C\u044B")
	@org.kie.api.definition.type.Position(11)
	private char insuranceProgramCode;

	@org.kie.api.definition.type.Label("\u043C\u0438\u043D\u0438\u043C\u0430\u043B\u044C\u043D\u044B\u0439 \u0441\u0440\u043E\u043A \u043F\u043E \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0443")
	@org.kie.api.definition.type.Position(12)
	private java.lang.Integer minProductTerm;

	@org.kie.api.definition.type.Label("\u043C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u044B\u0439 \u0441\u0440\u043E\u043A \u043F\u043E \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0443")
	@org.kie.api.definition.type.Position(13)
	private java.lang.Integer maxProductTerm;

	@org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0442\u043E\u0447\u043A\u0438 \u043F\u0440\u043E\u0434\u0430\u0436\u0438 \u041C\u0424\u041E")
	@org.kie.api.definition.type.Position(14)
	private java.lang.Integer POSIdMFI;

	public java.util.Date getApplicationCreateDate() {
        return this.applicationCreateDate;
    }
    
    public void setApplicationCreateDate(java.util.Date applicationCreateDate) {
        this.applicationCreateDate = applicationCreateDate;
    }

    public char getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(char applicationId) {
        this.applicationId = applicationId;
    }

    public java.lang.Integer getBaseInterestRate() {
		return this.baseInterestRate;
	}

	public void setBaseInterestRate(java.lang.Integer baseInterestRate) {
		this.baseInterestRate = baseInterestRate;
	}

	public java.lang.Integer getInsuranceAmount() {
		return this.insuranceAmount;
	}

	public void setInsuranceAmount(java.lang.Integer insuranceAmount) {
		this.insuranceAmount = insuranceAmount;
	}

	public java.lang.Integer getRequestedAmount() {
		return this.requestedAmount;
	}

	public void setRequestedAmount(java.lang.Integer requestedAmount) {
		this.requestedAmount = requestedAmount;
	}

	public java.lang.Integer getMinProductTerm() {
		return this.minProductTerm;
	}

	public void setMinProductTerm(java.lang.Integer minProductTerm) {
		this.minProductTerm = minProductTerm;
	}

	public java.lang.Integer getMaxProductTerm() {
		return this.maxProductTerm;
	}

	public void setMaxProductTerm(java.lang.Integer maxProductTerm) {
		this.maxProductTerm = maxProductTerm;
	}

	public java.lang.Integer getPOSIdMFI() {
		return this.POSIdMFI;
	}

	public void setPOSIdMFI(java.lang.Integer POSIdMFI) {
		this.POSIdMFI = POSIdMFI;
	}

	public java.lang.Integer getRequestedRate() {
		return this.requestedRate;
	}

	public void setRequestedRate(java.lang.Integer requestedRate) {
		this.requestedRate = requestedRate;
	}

	public java.lang.Integer getRequestedMaturity() {
		return this.requestedMaturity;
	}

	public void setRequestedMaturity(java.lang.Integer requestedMaturity) {
		this.requestedMaturity = requestedMaturity;
	}

	public com.fourlt.reference.currencyCode getRequestedCurrencyId() {
		return this.requestedCurrencyId;
	}

	public void setRequestedCurrencyId(
			com.fourlt.reference.currencyCode requestedCurrencyId) {
		this.requestedCurrencyId = requestedCurrencyId;
	}

	public char getRequestedProductId() {
		return this.requestedProductId;
	}

	public void setRequestedProductId(char requestedProductId) {
		this.requestedProductId = requestedProductId;
	}

	public char getInsuranceProgramCode() {
		return this.insuranceProgramCode;
	}

	public void setInsuranceProgramCode(char insuranceProgramCode) {
		this.insuranceProgramCode = insuranceProgramCode;
	}

	public char getInsuranceCompanyId() {
		return this.insuranceCompanyId;
	}

	public void setInsuranceCompanyId(char insuranceCompanyId) {
		this.insuranceCompanyId = insuranceCompanyId;
	}

	public char getContractTypeMFI() {
		return this.contractTypeMFI;
	}

	public void setContractTypeMFI(char contractTypeMFI) {
		this.contractTypeMFI = contractTypeMFI;
	}

	public ApplicationProduct() {
	}

	public ApplicationProduct(char applicationId,
			java.util.Date applicationCreateDate, char requestedProductId,
			java.lang.Integer requestedAmount,
			com.fourlt.reference.currencyCode requestedCurrencyId,
			java.lang.Integer requestedRate,
			java.lang.Integer requestedMaturity,
			java.lang.Integer baseInterestRate, char contractTypeMFI,
			java.lang.Integer insuranceAmount, char insuranceCompanyId,
			char insuranceProgramCode, java.lang.Integer minProductTerm,
			java.lang.Integer maxProductTerm, java.lang.Integer POSIdMFI) {
		this.applicationId = applicationId;
		this.applicationCreateDate = applicationCreateDate;
		this.requestedProductId = requestedProductId;
		this.requestedAmount = requestedAmount;
		this.requestedCurrencyId = requestedCurrencyId;
		this.requestedRate = requestedRate;
		this.requestedMaturity = requestedMaturity;
		this.baseInterestRate = baseInterestRate;
		this.contractTypeMFI = contractTypeMFI;
		this.insuranceAmount = insuranceAmount;
		this.insuranceCompanyId = insuranceCompanyId;
		this.insuranceProgramCode = insuranceProgramCode;
		this.minProductTerm = minProductTerm;
		this.maxProductTerm = maxProductTerm;
		this.POSIdMFI = POSIdMFI;
	}

}