package application;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("\u041A\u0440\u0435\u0434\u0438\u0442\u043D\u043E\u0435\u0420\u0435\u0448\u0435\u043D\u0438\u0435")
public class ScoringDecision extends application.ApplicationProduct implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F\u0421\u0443\u043C\u043C\u0430")
	@org.kie.api.definition.type.Position(1)
	private java.lang.Integer approvedAmount;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F\u0412\u0430\u043B\u044E\u0442\u0430")
	@org.kie.api.definition.type.Position(4)
	private com.fourlt.reference.currencyCode approvedCurrency;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u044B\u0439\u0421\u0440\u043E\u043A")
	@org.kie.api.definition.type.Position(2)
	private java.lang.Integer approvedMaturity;

    @org.kie.api.definition.type.Label("\u041E\u0434\u043E\u0431\u0440\u0435\u043D\u043D\u0430\u044F\u0421\u0442\u0430\u0432\u043A\u0430")
	@org.kie.api.definition.type.Position(3)
	private java.lang.Integer approvedRate;

    @org.kie.api.definition.type.Label("\u0414\u0430\u0442\u0430\u041A\u0440\u0435\u0434\u0438\u0442\u043D\u043E\u0433\u043E\u0420\u0435\u0448\u0435\u043D\u0438\u044F")
	@org.kie.api.definition.type.Position(0)
	private java.util.Date decisionDate;

    @org.kie.api.definition.type.Label(value = "\u0438\u0434 \u0437\u0430\u044F\u0432\u043A\u0438")
	@org.kie.api.definition.type.Position(value = 5)
	private char applicationId;

	public java.lang.Integer getApprovedAmount() {
        return this.approvedAmount;
    }
    
    public void setApprovedAmount(java.lang.Integer approvedAmount) {
        this.approvedAmount = approvedAmount;
    }

    public com.fourlt.reference.currencyCode getApprovedCurrency() {
        return this.approvedCurrency;
    }
    
    public void setApprovedCurrency(com.fourlt.reference.currencyCode approvedCurrency) {
        this.approvedCurrency = approvedCurrency;
    }

    public java.lang.Integer getApprovedMaturity() {
        return this.approvedMaturity;
    }
    
    public void setApprovedMaturity(java.lang.Integer approvedMaturity) {
        this.approvedMaturity = approvedMaturity;
    }

    public java.lang.Integer getApprovedRate() {
        return this.approvedRate;
    }
    
    public void setApprovedRate(java.lang.Integer approvedRate) {
        this.approvedRate = approvedRate;
    }

    public java.util.Date getDecisionDate() {
        return this.decisionDate;
    }
    
    public void setDecisionDate(java.util.Date decisionDate) {
        this.decisionDate = decisionDate;
    }

	public char getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(char applicationId) {
		this.applicationId = applicationId;
	}

	public ScoringDecision() {
	}

	public ScoringDecision(java.util.Date decisionDate,
			java.lang.Integer approvedAmount,
			java.lang.Integer approvedMaturity, java.lang.Integer approvedRate,
			com.fourlt.reference.currencyCode approvedCurrency,
			char applicationId) {
		this.decisionDate = decisionDate;
		this.approvedAmount = approvedAmount;
		this.approvedMaturity = approvedMaturity;
		this.approvedRate = approvedRate;
		this.approvedCurrency = approvedCurrency;
		this.applicationId = applicationId;
	}

}