package com.fourlt.reference;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "\u0441\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A \u0432\u0430\u043B\u044E\u0442")
public class currencyCode implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public currencyCode() {
    }

}