package com.fourlt.reference;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("\u0441\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A \u0442\u0438\u043F\u043E\u0432 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u043E\u0432")
public class SubjectType implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("\u043A\u043E\u0434 \u0442\u0438\u043F\u0430 \u0441\u0443\u0431\u044A\u0435\u043A\u0442\u0430")
	@org.kie.api.definition.type.Position(0)
	private java.lang.Integer subjectTypeCode;
	@org.kie.api.definition.type.Label("\u043D\u0430\u0438\u043C\u0435\u043D\u043E\u0432\u0430\u043D\u0438\u0435 \u0442\u0438\u043F\u0430")
	@org.kie.api.definition.type.Position(1)
	private char typeName;

	public java.lang.Integer getSubjectTypeCode() {
		return this.subjectTypeCode;
	}

	public void setSubjectTypeCode(java.lang.Integer subjectTypeCode) {
		this.subjectTypeCode = subjectTypeCode;
	}

	public char getTypeName() {
		return this.typeName;
	}

	public void setTypeName(char typeName) {
		this.typeName = typeName;
	}

	public SubjectType() {
	}

	public SubjectType(java.lang.Integer subjectTypeCode, char typeName) {
		this.subjectTypeCode = subjectTypeCode;
		this.typeName = typeName;
	}

}